if has('win32') || has('win64')
    set runtimepath=$HOME/.vim,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,$HOME/.vim/after
endif

syntax on
color dracula

set tabstop=4
set softtabstop=0 noexpandtab
set shiftwidth=4
